version: '3.2'
services:
  grafana:
    image: grafana/grafana  
    
    depends_on:
      - prometheus
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml    
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
    - elliottsmetrics-cadvisor
    
  elliottsmetrics-cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: elliottsmetrics-cadvisor #cadvisor 
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw  #volume mappping for mac
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  #   depends_on:
  #   - redis
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #   - 6379:6379